name: Code Check & Format

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install leptosfmt
        run: cargo install leptosfmt --locked

      - name: Check format (rustfmt+leptosfmt)
        run: cargo fmt --all

      - name: Clippy check
        run: cargo clippy --all -- -D warnings